### PR TITLE
Add languages TOC linked to separate sections

### PR DESCRIPTION
**Pull request by HannahKirk**

### CODE REVIEW

**Comment by leondz** [comment]
thanks! this addresses issue #16. can you undo the line that clobbers the new credits at the top?

**Comment by leondz** [comment]
see line 7 in https://github.com/leondz/hatespeechdata/pull/49/commits/156a13dff5678a50c513591fbd434281fade3117

**Comment by HannahKirk** [comment]
Should be sorted now

**Comment by leondz** [comment]
thanks :)

**Pull request merged**
